# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '2e28c82c-17d7-4303-b27a-4141b3d4088f'

  # Web app name
  webAppName: 'saanvikit-petclinic'

  # Environment name
  environmentName: 'develop'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:

  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)

    steps:
    - checkout: self
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          # - task: DownloadBuildArtifacts@1
          #   displayName: 'Download build artifacts'
          #   inputs:
          #     buildType: 'current'
          #     downloadType: 'single'
          #     artifactName: 'drop'
          #     downloadPath: '$(System.DefaultWorkingDirectory)'
          
          - task: AzureRmWebAppDeployment@5
            displayName: 'Azure web app deploy: saanvikit-petclinic'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'saanvikit-azure-connection'
              appType: 'webAppLinux'
              WebAppName: 'saanvikit-petclinic'
              packageForLinux: '$(System.DefaultWorkingDirectory)/drop/target/*.?(war|jar)'
              DeploymentTypeLinux: 'oneDeploy'

          # - task: AzureWebApp@1
          #   displayName: 'Azure Web App Deploy: saanvikit-app'
          #   inputs:
          #     azureSubscription: $(saanvikit-azure-connection)
          #     appType: webAppLinux
          #     appName: $(webAppName)
          #     package: '$(System.DefaultWorkingDirectory)/drop/*.?(war|jar)'
